server:
  port: 18086

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: localhost:8848
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  feign:
    sentinel:
      enabled: true
  elasticsearch:
    rest:
      uris: 47.105.51.163:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 47.105.51.163
    username: mj
    password: majie123
    virtual-host: /mj
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1