server:
  port: 18090

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: localhost:8848
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: localhost:9411
    sender:
      type: web
    discovery-client-enabled: false

  feign:
    sentinel:
      enabled: true
  redis:
    port: 6379
    host: 192.168.137.131
  thymeleaf:
    cache: false

  rabbitmq:
    host: 120.26.179.107
    username: mj
    password: majie123
    virtual-host: /mj
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
    publisher-confirm-type: simple
    publisher-returns: true

threadPool:
  coreSize: 100
  maxSize: 200
  timeout: 60
  blockingSize: 1000

auth:
  jwt:
    pubKeyPath: F:\ideaproject\guli_gmall\rsa\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: userKey
