server:
  port: 18089

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: localhost:8848
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart
    username: root
  feign:
    sentinel:
      enabled: true
  redis:
    port: 6379
    host: 192.168.137.131
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 80
        max-size: 200
        keep-alive: 90s
        queue-capacity: 1000
        # 是否允许连接超时不关闭
        allow-core-thread-timeout: true
      shutdown:
        # 关闭之前，是否等待子任务完成
        await-termination: true
        # 等待子任务完成的时间
        await-termination-period: 90
  rabbitmq:
    host: 47.105.51.163
    username: mj
    password: majie123
    virtual-host: /mj
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual

mybatis-plus:
 # configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:mapper/cart/**/*.xml
  #别名扫描   设置了这个，在mapper文件中，就可以不用写全类名了，会到这个包下找
  type-aliases-package: com.atguigu.gmall.cart.mapper
  global-config:
    db-config:
      id-type: auto

auth:
  jwt:
    pubKeyPath: F:\ideaproject\guli_gmall\rsa\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: userKey
