server:
  port: 18085

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  feign:
    sentinel:
      enabled: true

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/guli_oms
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.137.131
  rabbitmq:
    host: 120.26.179.107
    username: mj
    password: majie123
    virtual-host: /mj
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
    publisher-confirm-type: simple
    publisher-returns: true

mybatis-plus:
  mapper-locations: classpath:mapper/oms/**/*.xml
  type-aliases-package: com.atguigu.gmall.oms.entity
  global-config:
    db-config:
      id-type: auto
