server:
  port: 8888

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums
          uri: ln://ums-service
          predicates:
            - Path=/ums/**
        - id: wms
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms
          uri: lb://oms-service
          predicates:
            - Path=/oms/**

