server:
  port: 8888

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums
          uri: ln://ums-service
          predicates:
            - Path=/ums/**
        - id: wms
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: search
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com,gmall.com
        - id: index
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item
          uri: lb://item-service
          predicates:
            - Path=/item/**

