server:
  port: 8888

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums
          uri: ln://ums-service
          predicates:
            - Path=/ums/**
        - id: wms
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: search
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com,gmall.com
#          filters:
#            - Auth=/aa,/bb,/cc
        - id: index2
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: sso
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: order
          uri: lb://order-service
          predicates:
            - Host=order.gmall.com
          filters:
            - Auth=/

auth:
  jwt:
    pubKeyPath: F:\ideaproject\guli_gmall\rsa\rsa.pub
    cookieName: GMALL-TOKEN