server:
  port: 18088

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: localhost:8848
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  feign:
    sentinel:
      enabled: true
  thymeleaf:
    cache: false

auth:
  jwt:
    pubKeyPath: F:\ideaproject\guli_gmall\rsa\rsa.pub
    priKeyPath: F:\ideaproject\guli_gmall\rsa\rsa.pri
    secret: 14250^*(#&*@.;`wcnm
    cookieName: GMALL-TOKEN
    expire: 180
    unick: unick