server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_wms
    username: root
    password: root
  redis:
    host: 192.168.137.131
  rabbitmq:
    host: 120.26.179.107
    username: mj
    password: majie123
    virtual-host: /mj
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
    publisher-confirm-type: simple
    publisher-returns: true

feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  type-aliases-package: com.atguigu.gamll.wmsinterface.entity
  global-config:
    db-config:
      id-type: auto